# Name:Shruti Pardeshi
# Branch: IT

In [1]:
import numpy as np

In [5]:
arr = np.array([1,3,5,6])

In [6]:
arr

array([1, 3, 5, 6])

In [31]:
np.average(arr)

np.float64(3.75)

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.arange(3,100,6)

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99])

In [13]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

In [14]:
result = np.cross(a, b)
print(result)

[0 0 1]


In [15]:
np.dot(a, b)

np.int64(0)

In [16]:
np.outer(a, b)

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
np.linalg.norm(a)  

np.float64(1.0)

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
d = np.array([[13, 14], [15, 16]])
result = np.block([
    [a,b],
    [c,d]
])
print(result)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]


In [30]:
block_matrix = np.bmat([[a, b],[c, d]])
print(block_matrix)

[[ 1  2  1  5]
 [ 3  4  7  3]
 [ 9 10 13 14]
 [11 12 15 16]]


In [21]:
np.random.rand(2, 2)

array([[0.8671352 , 0.61456081],
       [0.16324427, 0.36429662]])

In [22]:
index = [0, 1, 0, 1]
c1 = [10, 20, 30, 40]
c2 = [100, 200, 300, 400]

In [23]:
result = np.choose(index, [c1, c2])
print(result)

[ 10 200  30 400]


In [24]:
np.size(a) 

4

In [25]:
a = np.array([[1, 2], [3, 4]])
a.shape 

(2, 2)

In [26]:
np.ndim(a)

2

In [27]:
s = np.array([4, 1, 9, 6])
result = np.amax(s)
print(result)

9


In [28]:
b = np.array([[1, 5], [7, 3]])
row_max = np.amax(b, axis=1)  
col_max = np.amax(b, axis=0)  
print("Row max:", row_max)
print("Col max:", col_max)

Row max: [5 7]
Col max: [7 5]


In [29]:
np.round(5.6789, 2)

np.float64(5.68)

In [32]:
a = np.array([3, 7, 1, 9, 5])
print(np.amax(a))

9


In [34]:
print(np.amin(a))

1


In [35]:
print(np.append(a, [4, 5]))

[3 7 1 9 5 4 5]


In [38]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 5])
print(np.equal(x, y))

[ True False  True False]


In [39]:
np.clip(x, 3, 7)

array([3, 3, 3, 4])

In [40]:
np.geterr()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [41]:
np.seterr(divide='raise', over='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [44]:
buffer_size = x.nbytes
print(buffer_size)

32


In [45]:
data = np.array([x, y])
cov_matrix = np.cov(data)
print(cov_matrix)

[[1.66666667 2.5       ]
 [2.5        4.91666667]]


In [46]:
np.greater(x,y)

array([False,  True, False, False])

In [47]:
np.gradient(x)

array([1., 1., 1., 1.])

In [49]:
np.histogramdd(x, bins=10, range=None)

(array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1.]),
 [array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ])])

In [52]:
np.hsplit(x, 2)

[array([1, 2]), array([3, 4])]

In [55]:
np.hstack(x)

array([1, 2, 3, 4])

In [56]:
np.hypot(x,y)

array([1.41421356, 2.        , 4.24264069, 6.40312424])